#!/bin/bash
set -e
python ../scripts/scanner.py
python ../scripts/gen6502.py
pushd ../runtime >/dev/null
./build -q
cp runtime.prg ../compiler
popd >/dev/null
python block.py

../bin/x16emu -debug -prg application.prg -scale 2 -run