#!/bin/bash
set -e
rm *.prg
python ../scripts/scanner.py
python ../scripts/gen6502.py
pushd ../runtime >/dev/null
./build -q
cp runtime.prg ../compiler
popd >/dev/null
make -s
python amoral.zip -s -o test.prg benchmark.amo
../bin/x16emu -debug -prg test.prg -scale 2 -run